# Generated by Django 3.2.12 on 2022-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opportunityproducts',
            unique_together={('opportunity', 'name')},
        ),
    ]
