# Generated by Django 3.2.12 on 2022-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_opportunityproducts_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='newly_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='to_be_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
